# Generated by Django 5.1.3 on 2024-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yazlab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kullanici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kullanici_adi", models.CharField(max_length=150, unique=True)),
                ("sifre", models.CharField(max_length=128)),
                ("eposta", models.EmailField(max_length=254, unique=True)),
                ("konum", models.CharField(blank=True, max_length=255, null=True)),
                ("ilgi_alanlari", models.TextField(blank=True, null=True)),
                ("ad", models.CharField(max_length=50)),
                ("soyad", models.CharField(max_length=50)),
                ("dogum_tarihi", models.DateField()),
                ("cinsiyet", models.CharField(max_length=10)),
                ("telefon_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "profil_fotografi",
                    models.ImageField(
                        blank=True, null=True, upload_to="profil_fotograflari/"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OrnekModel",
        ),
    ]
