# Generated by Django 5.1.3 on 2024-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('yazlab', '0002_kullanici_delete_ornekmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('tarih', models.DateField()),
                ('aciklama', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='sifre',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='konum',
        ),
        migrations.AddField(
            model_name='kullanici',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='kullanici_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='kullanici_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='cinsiyet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
